import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'pau' at '12/4/15 10:21 PM' with Gradle 2.8
 *
 * @author pau, @date 12/4/15 10:21 PM
 */
public class NaMvcControllerTest {
    @Test public void testSomeLibraryMethod() {
        //Library classUnderTest = new Library();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
